### PR TITLE
Remove migrate.load plugin type

### PR DESCRIPTION
**Pull request by Berdir**

### CODE REVIEW

**Comment by bartfeenstra** [comment]
Why?

**Comment by Berdir** [comment]
Because they have been removed in https://www.drupal.org/node/2549013 :)

Did run into this when updating a site from beta14 to rc1.

**Comment by bartfeenstra** [comment]
Understood.

None that Plugin development still takes place on drupal.org, because it doesn't fully work with Travis CI yet (Simpletest tests are not run).

**Comment by Berdir** [comment]
Ok, opened https://www.drupal.org/node/2600820

**Pull request closed without merging**
